/**
 * generate-skill-docs.ts
 *
 * Derives the schema-driven parts of the `demopilot-demo-scripts` Claude Code
 * skill straight from the Zod schema in `packages/core/src/schema.ts` (the
 * single source of truth for the demo-script format). Run it whenever that
 * schema changes so the skill never drifts:
 *
 *     pnpm generate:skill-docs
 *
 * A PostToolUse hook (.claude/hooks/sync-skill-docs.sh) runs this automatically
 * when an agent edits the schema during a Claude Code session.
 *
 * Outputs (all carry a "do not hand-edit" banner — edit schema.ts instead):
 *   .claude/skills/demopilot-demo-scripts/references/script-schema.md
 *   .claude/skills/demopilot-demo-scripts/templates/minimal.yaml
 *   .claude/skills/demopilot-demo-scripts/templates/full-with-defaults.yaml
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import {
  DemoDefaultsSchema,
  DemoScriptSchema,
  StepSchema,
  TargetSchema,
} from "../packages/core/src/schema.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const skillDir = join(repoRoot, ".claude", "skills", "demopilot-demo-scripts");

const BANNER =
  "<!-- GENERATED by scripts/generate-skill-docs.ts — do not hand-edit. " +
  "Change packages/core/src/schema.ts and run `pnpm generate:skill-docs`. -->";
const YAML_BANNER =
  "# GENERATED by scripts/generate-skill-docs.ts — do not hand-edit.\n" +
  "# Change packages/core/src/schema.ts and run `pnpm generate:skill-docs`.";

// ---------------------------------------------------------------------------
// Tiny Zod introspection helpers. We unwrap optional/default/effects wrappers
// to reach the inner type so we can describe its kind, enum values, range, and
// default — everything an author needs, read straight from the schema.
// ---------------------------------------------------------------------------

interface FieldInfo {
  type: string;
  optional: boolean;
  default?: unknown;
  description?: string;
}

function unwrap(schema: z.ZodTypeAny): {
  inner: z.ZodTypeAny;
  optional: boolean;
  default?: unknown;
  description?: string;
} {
  let current = schema;
  let optional = false;
  let def: unknown;
  let description = current._def?.description as string | undefined;

  // Peel ZodOptional / ZodDefault / ZodEffects (refine) wrappers.
  // ZodDefault carries the default value; ZodOptional marks the field optional.
  for (let guard = 0; guard < 10; guard++) {
    const typeName = current._def?.typeName;
    description ||= current._def?.description as string | undefined;
    if (typeName === "ZodOptional") {
      optional = true;
      current = current._def.innerType;
    } else if (typeName === "ZodDefault") {
      def = current._def.defaultValue();
      current = current._def.innerType;
    } else if (typeName === "ZodEffects") {
      current = current._def.schema;
    } else {
      break;
    }
  }
  description ||= current._def?.description as string | undefined;
  return { inner: current, optional, default: def, description };
}

function describeType(schema: z.ZodTypeAny): string {
  const typeName = schema._def?.typeName;
  switch (typeName) {
    case "ZodString":
      return "string";
    case "ZodBoolean":
      return "boolean";
    case "ZodNumber": {
      const checks = (schema._def.checks ?? []) as Array<{ kind: string; value?: number }>;
      const isInt = checks.some((c) => c.kind === "int");
      const min = checks.find((c) => c.kind === "min")?.value;
      const max = checks.find((c) => c.kind === "max")?.value;
      let label = isInt ? "integer" : "number";
      if (min !== undefined || max !== undefined) {
        label += ` (${min ?? "−∞"}–${max ?? "∞"})`;
      }
      return label;
    }
    case "ZodEnum":
      return `enum: ${(schema._def.values as string[]).map((v) => `\`${v}\``).join(" | ")}`;
    case "ZodLiteral":
      return `literal \`${JSON.stringify(schema._def.value)}\``;
    case "ZodArray":
      return `array of ${describeType(schema._def.type)}`;
    case "ZodObject":
      return "object";
    case "ZodUnion":
      return [...new Set((schema._def.options as z.ZodTypeAny[]).map(describeType))].join(" | ");
    default:
      return typeName ?? "unknown";
  }
}

function fieldInfo(schema: z.ZodTypeAny): FieldInfo {
  const { inner, optional, default: def, description } = unwrap(schema);
  return { type: describeType(inner), optional, default: def, description };
}

/** Render an object schema's fields as a Markdown table. */
function objectTable(schema: z.ZodObject<z.ZodRawShape>, withDefault = false): string {
  const shape = schema.shape;
  const header = withDefault
    ? "| Field | Type | Required | Default | Description |\n| --- | --- | --- | --- | --- |"
    : "| Field | Type | Required | Description |\n| --- | --- | --- | --- |";
  const rows = Object.entries(shape).map(([key, value]) => {
    const info = fieldInfo(value as z.ZodTypeAny);
    const required = info.optional || info.default !== undefined ? "" : "✓";
    const type = info.type.replace(/\|/g, "\\|");
    const desc = (info.description ?? "").replace(/\|/g, "\\|");
    if (withDefault) {
      const dflt = info.default !== undefined ? `\`${JSON.stringify(info.default)}\`` : "";
      return `| \`${key}\` | ${type} | ${required} | ${dflt} | ${desc} |`;
    }
    return `| \`${key}\` | ${type} | ${required} | ${desc} |`;
  });
  return [header, ...rows].join("\n");
}

// ---------------------------------------------------------------------------
// Step catalog — walk each variant of the StepSchema union.
// ---------------------------------------------------------------------------

function stepCatalog(): string {
  const variants = StepSchema._def.options as z.ZodTypeAny[];
  const out: string[] = [];
  for (const variant of variants) {
    // Each variant is a strict object with exactly one action key.
    const shape = (variant as z.ZodObject<z.ZodRawShape>).shape;
    const key = Object.keys(shape)[0];
    const valueSchema = shape[key] as z.ZodTypeAny;
    const { inner, description } = unwrap(valueSchema);
    out.push(`### \`${key}\``);
    out.push("");
    if (description) out.push(`${description}\n`);

    const innerName = inner._def?.typeName;
    if (innerName === "ZodObject") {
      out.push(objectTable(inner as z.ZodObject<z.ZodRawShape>));
    } else {
      // Scalar / enum / union step (goto, pause, narrate, zoom, group).
      out.push(`Value: ${describeType(inner)}`);
    }
    out.push("");
  }
  return out.join("\n");
}

// ---------------------------------------------------------------------------
// Reference doc.
// ---------------------------------------------------------------------------

function referenceMarkdown(): string {
  const topShape = DemoScriptSchema.shape;
  const viewport = unwrap(topShape.viewport).inner as z.ZodObject<z.ZodRawShape>;
  const zoom = unwrap((DemoDefaultsSchema.shape.zoom as z.ZodTypeAny)).inner as z.ZodObject<
    z.ZodRawShape
  >;

  return `${BANNER}

# DemoPilot demo-script format reference

This file is generated from \`packages/core/src/schema.ts\`. It always matches the
schema the renderer validates against. Use it as the authoritative field list;
see \`../SKILL.md\` for guidance and \`../templates/\` for copy-paste starters.

## Top-level script

${objectTable(DemoScriptSchema)}

\`viewport\` shape (default \`{ width: 1280, height: 800 }\`):

${objectTable(viewport)}

## Steps

\`steps\` is a non-empty array. Each step is an object with **exactly one** action
key (one-key shorthand). The available step kinds:

${stepCatalog()}

## Targets

Several steps take a \`target\` that identifies an element. Prefer accessibility
(\`role\` + \`name\`) — it survives markup churn far better than CSS. \`css\` and
\`testId\` are escape hatches. **A target needs at least one of: \`role\`, \`name\`,
\`text\`, \`css\`, \`testId\`.**

${objectTable(unwrap(TargetSchema).inner as z.ZodObject<z.ZodRawShape>)}

## Defaults

All optional; omit the \`defaults:\` block entirely to run on DemoPilot's calibrated
defaults.

${objectTable(DemoDefaultsSchema, true)}

### \`defaults.zoom\` (post-production camera)

Applied by the compositor, not playback. The camera holds one anchor across each
action group, then springs/pans to the next; depth is chosen automatically from
the acted-on element's size.

${objectTable(zoom, true)}
`;
}

// ---------------------------------------------------------------------------
// Templates.
// ---------------------------------------------------------------------------

function minimalTemplate(): string {
  return `${YAML_BANNER}
#
# Minimal accessibility-first starter. Prefer role+name targets; use waitFor
# after async/navigation; wrap multi-step flows in a named group so the camera
# holds one anchor. Runs entirely on DemoPilot's built-in defaults.
name: My demo
description: One-line summary of what this demo shows.
baseUrl: http://localhost:4321
steps:
  - goto: /
  - narrate: First, create your account
  - group: { name: Sign in }
  - type:
      target: { role: textbox, name: Email }
      text: demo@acme.com
  - type:
      target: { role: textbox, name: Password }
      text: hunter2demo
  - click:
      target: { role: button, name: Create account }
  - group: end
  - waitFor:
      target: { text: Welcome to Acme }
  - narrate: You're in!
`;
}

function fullTemplate(): string {
  const d = DemoDefaultsSchema.parse({});
  const z = d.zoom;
  return `${YAML_BANNER}
#
# Every top-level field plus a defaults block populated with the schema's current
# default values (so this example never lists a stale default). Delete the
# defaults you don't need to override — omitting them runs on the same values.
name: Full reference demo
description: Shows every script field with its default-valued defaults block.
baseUrl: http://localhost:4321
viewport:
  width: 1280
  height: 800
# storageStatePath: ./auth/storageState.json   # for pre-authenticated demos
defaults:
  typeCadence: ${d.typeCadence}
  mousePace: ${d.mousePace}
  readPause: ${d.readPause}
  preActionDwell: ${d.preActionDwell}
  postActionHold: ${d.postActionHold}
  speed: ${d.speed}
  zoom:
    level: ${z.level}
    minZoom: ${z.minZoom}
    maxZoom: ${z.maxZoom}
    fill: ${z.fill}
    establishLevel: ${z.establishLevel}
    panThreshold: ${z.panThreshold}
    stiffness: ${z.stiffness}
    damping: ${z.damping}
    groupGapMs: ${z.groupGapMs}
    cursorScale: ${z.cursorScale}
steps:
  - goto: /
  - narrate: Walking through the full step vocabulary
  - hover:
      target: { role: button, name: Menu }
  - click:
      target: { role: button, name: Menu }
  - type:
      target: { role: textbox, name: Search }
      text: hello
      cadence: human
  - press:
      keys: Enter
  - select:
      target: { role: combobox, name: Sort }
      label: Newest
  - scroll:
      to: bottom
  - zoom: in
  - waitFor:
      target: { text: Results }
      state: visible
  - zoom: out
  - pause: 400
`;
}

// ---------------------------------------------------------------------------
// Write outputs.
// ---------------------------------------------------------------------------

function write(relPath: string, contents: string): void {
  const full = join(skillDir, relPath);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, contents.endsWith("\n") ? contents : `${contents}\n`);
  console.log(`wrote ${full.replace(`${repoRoot}/`, "")}`);
}

write("references/script-schema.md", referenceMarkdown());
write("templates/minimal.yaml", minimalTemplate());
write("templates/full-with-defaults.yaml", fullTemplate());
console.log("skill docs generated.");
